version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./docker-postgres/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # Need help with this
  # azurite:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   container_name: "azurite"
  #   hostname: azurite
  #   restart: always
  #   ports:
  #     - "10000:10000"
  #     - "10001:10001"
  #     - "10002:10002"
